Add complete and self-contained mac target. Has external dependency on patchqmake source download pending license clarification.
git-svn-id: https://sctime.svn.sourceforge.net/svnroot/sctime/trunk/sctime@219 0511fff6-642a-0410-b4b1-cbf9baaaddce

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+# On Mac OS X we build nicely without all the cruft below
+if uname | grep Darwin >/dev/null 2>&1 ; then
+	qmake -makefile $* sctime.pro || echo "qmake failed!"
+	exit 0
+fi
+
 arch=$1
 
 if [[ -z $arch ]] ; then
