make it possible to pass options to qmake via configure
git-svn-id: https://sctime.svn.sourceforge.net/svnroot/sctime/trunk/sctime@37 0511fff6-642a-0410-b4b1-cbf9baaaddce

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,14 +1,17 @@
 #!/bin/ksh
 
-if [[ -z $1 ]] ; then
+arch=$1
+
+if [[ -z $arch ]] ; then
    echo "Syntax: ./configure <architecture>"
    echo "architecture may be one of the follwing values:"
-   \ls -1 ./mkspecs/$1
+   \ls -1 ./mkspecs/$arch
    exit 1 ;
 fi
-if [[ ! -d ./mkspecs/$1 ]] ; then
-   echo "Unknown architecture \"$1\""
+shift
+if [[ ! -d ./mkspecs/$arch ]] ; then
+   echo "Unknown architecture \"$arch\""
    exit 2 ;
 fi
 echo "Running qmake"
-qmake -makefile -spec `pwd`/mkspecs/$1 sctime.pro || echo "qmake failed!"
+qmake -makefile -spec `pwd`/mkspecs/$arch $* sctime.pro || echo "qmake failed!"
